### ISSUE TITLE
.NET 3.9 API Link is dead

### ISSUE THREAD

**Issue by dsaf** [bloomberg/bloomberg.github.io#1]
Java and C++ work:

http://bloomberg.github.io/blpapi-docs/java/3.9/

http://bloomberg.github.io/blpapi-docs/cpp/3.9/

C# doesn't:

http://bloomberg.github.io/blpapi-docs/dotnet/3.9/

![image](https://cloud.githubusercontent.com/assets/3845650/12486237/a6bebc14-c059-11e5-9388-361ea891cb78.png)

**Comment by kpfleming** [comment]
Thanks, will get this corrected.

**Comment by kpfleming** [comment]
For now we've removed the link from the page, as the API SDK team is still investigating what changed between the 3.8 and 3.9 releases.
